### PR TITLE
added attack names and log

### PR DESCRIPTION
**Pull request by Arciles**
log is added both cthulhu and player which records their attack.

### CODE REVIEW

**Comment by devolasvegas** [comment]
GitHub tells me that this branch "has conflicts that must be resolved."

**Comment by Arciles** [comment]
I don't know what is the problem. I can send the pull request again if you want.

**Comment by devolasvegas** [comment]
Yeah, maybe try again? This is the message that I get: 
This branch has conflicts that must be resolved
 Use the command line to resolve conflicts before continuing.

**Comment by Arciles** [comment]
can you decline my pull request?

**Comment by devolasvegas** [comment]
I don't think so. Tried opening it in the desktop app.

**Comment by Arciles** [comment]
we'll try to fix it tomorrow. is it okay?

**Comment by devolasvegas** [comment]
Yeah, that sounds like a good idea. It's probably nothing too complex.

**Pull request closed without merging**
